In [44]:
from keras import backend as K
import tensorflow as tf
import numpy as np

In [6]:
# learn how to use eval to print the variables
kvar = K.variable(np.array([[1, 2], [3, 4]]), dtype='float32')
print "after create the tensor", kvar
print "use eval to print the vaule", K.eval(kvar)

after create the tensor <tf.Variable 'Variable_2:0' shape=(2, 2) dtype=float32_ref>
use eval to print the vaule [[ 1.  2.]
 [ 3.  4.]]


In [12]:
# learn how to use cast
c = K.variable(np.array([[1.2, 2], [3.1, 4]]), dtype='float32')
print "before cast, the float values as ", K.eval(c)
c_int = K.cast(c, dtype = "int16")
print "after cast, the int values as ", K.eval(c_int)

before cast, the float values as  [[ 1.20000005  2.        ]
 [ 3.0999999   4.        ]]
after cast, the int values as  [[1 2]
 [3 4]]


In [21]:
# learn how to use gather
var = K.variable(np.array([[1, 2, 3], [4, 5, 6]]), dtype='float32')
print "the var as ", K.eval(var)
print "indices by second column", K.eval(var[..., 1:2])
# print "indices by second column by gather", K.eval(K.gather(kvar, [1,2]))

 the var as  [[ 1.  2.  3.]
 [ 4.  5.  6.]]
indices by second column [[ 2.]
 [ 5.]]


In [25]:
# learn how to do sum
var =  K.variable(np.array([[1, 2, 3], [4, 5, 6]]), dtype='float32')
print "the var as ", K.eval(var)
print "sum by column", K.eval(K.sum(var, axis = -1, keepdims = True))


the var as  [[ 1.  2.  3.]
 [ 4.  5.  6.]]
sum by column [[  6.]
 [ 15.]]


In [37]:
# learn the repeat
mask =  K.variable(np.array([[1, 0, 0], [1, 0, 0]]), dtype='float32')
print "the single mask as ", K.eval(mask)
print "the scaled mask as ", K.eval(K.stack(K.repeat_elements(mask, 2, 0)))

the single mask as  [[ 1.  0.  0.]
 [ 1.  0.  0.]]
the scaled mask as  [[ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]]


In [53]:
# split data
mask =  K.variable(np.array([[1, 0, 0, 1, 0, 0]]), dtype='float32')
print "the single mask as ", K.eval(mask)
print "after split, the single mask as ", K.eval(K.stack(tf.split(mask, num_or_size_splits = 2, axis = -1)))
print "reshape, after split, the single mask as ", K.eval(K.reshape(mask, (2, -1, 3)))

the single mask as  [[ 1.  0.  0.  1.  0.  0.]]
after split, the single mask as  [[[ 1.  0.  0.]]

 [[ 1.  0.  0.]]]
reshape, after split, the single mask as  [[[ 1.  0.  0.]]

 [[ 1.  0.  0.]]]


In [63]:
# learn arange
print np.arange(0, 4, 1)
K.eval(K.arange(0, 4, 1))

[0 1 2 3]


array([0, 1, 2, 3], dtype=int32)

In [74]:
# learn tile
print np.tile([[1,0,0],[2,0,0]], (2,2))

[[1 0 0 1 0 0]
 [2 0 0 2 0 0]
 [1 0 0 1 0 0]
 [2 0 0 2 0 0]]


In [92]:
# sqrt
l = K.variable(np.array([[-11, 0, 0]]))
r = K.variable(np.array([[1, 0, 0]]))
# v = K.variable((l - r), dtype='float32')
print K.eval(K.sqrt(l - r))
print K.eval(K.sqrt(r - l))
print K.eval(K.sqrt(K.abs(l - r)))
print K.eval(K.sum(K.sqrt(K.abs(l - r))))
print K.eval(K.sum(K.sqrt(K.abs(l - r))))

[[ 0.  0.  0.]]
[[ 3.46410155  0.          0.        ]]
[[ 3.46410155  0.          0.        ]]
3.4641


In [95]:
l = K.variable(np.array([[-1, 0, 0]]))
r = K.variable(np.array([[1, 0, 0]]))
K.eval(K.sum(K.square(l - r)))

4.0

In [98]:
# learn round
K.eval(K.round(np.array([[-0.01, 0.0001, 0]]) * 100.0) / 100.0)

array([[-0.01,  0.  ,  0.  ]])

In [99]:
np.random.randint(0, 10, [3])

array([1, 5, 6])