# practise numpy

In [1]:
import numpy as np

In [8]:
x1 = np.array([1,2])
x2 = np.array([3,4])
X = (x1, x2)
X = [np.expand_dims(x, axis=0) for x in X]
np.asarray(X)

array([[[1, 2]],

       [[3, 4]]])

In [8]:
a = np.array([[0,1],[2,3]])
a = np.expand_dims(a, axis=0)
print a.shape

(1, 2, 2)


In [12]:
np.vstack([x1, x2])

array([[1, 2],
       [3, 4]])

In [11]:
type([x1,x2])

list

In [10]:
# type cast
a = np.array([1.1, 2.0])
ia = a.astype(np.int32)
print a, ia, a.dtype, ia.dtype

[ 1.1  2. ] [1 2] float64 int32


In [24]:
# reshape practise
o = np.array([1,2,3,4,5,6])
o_2_3 = o.reshape((2,3))
print "after 2x2", o_2_3.shape, o_2_3

#duplicate
o2 = np.array([o_2_3] * 5)
# o2 = np.repeat(o_2_3[:, :, np.newaxis], 4, axis=2)
print "after repect 2x3", o2.shape, o2


 after 2x2 (2, 3) [[1 2 3]
 [4 5 6]]
after repect 2x3 (5, 2, 3) [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [43]:
# paracise the one line hot
n_classes = 3
ys = np.array([1, 2, 0])
print np.reshape(ys, -1)
y_ = np.zeros((ys.shape[0], n_classes), dtype=np.float32)
print np.arange(n_classes)
# print "ravel", ys.ravel()
y_[np.arange(n_classes), ys] = 1
print y_
# after = np.(ys)

[1 2 0]
[0 1 2]
[[ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]]
