In [34]:
import numpy as np
import keras.backend as K

Using TensorFlow backend.


In [24]:
y0 = np.array([[1,0.5,0.5], [0,0,0], [0,0,0], [1, 0.2, 0.2]])
y1 = np.zeros((4,3))
y0_ = np.array([[0,0,0], [0,0,0], [0,0,0], [1, 0.3, 0.3]])
y1_ = np.zeros((4,3))

In [86]:
y = np.reshape([y0,y1],(2, 2, 2, 3))
y_ = np.reshape([y0_,y1_], (2, 2, 2, 3))
print("y:", y)
print("y_", y_)

('y:', array([[[[ 1. ,  0.5,  0.5],
         [ 0. ,  0. ,  0. ]],

        [[ 0. ,  0. ,  0. ],
         [ 1. ,  0.2,  0.2]]],


       [[[ 0. ,  0. ,  0. ],
         [ 0. ,  0. ,  0. ]],

        [[ 0. ,  0. ,  0. ],
         [ 0. ,  0. ,  0. ]]]]))
('y_', array([[[[ 0. ,  0. ,  0. ],
         [ 0. ,  0. ,  0. ]],

        [[ 0. ,  0. ,  0. ],
         [ 1. ,  0.3,  0.3]]],


       [[[ 0. ,  0. ,  0. ],
         [ 0. ,  0. ,  0. ]],

        [[ 0. ,  0. ,  0. ],
         [ 0. ,  0. ,  0. ]]]]))


In [99]:
# 测试location loss
should_be = (0.5 **2 + 0.5 ** 2 + 0.1 ** 2 + 0.1 ** 2 ) / 2
print("should be", should_be)
filters = y[...,0:1]
np.mean(np.sum(np.sum(np.sum(np.square(y[..., 1:3] * filters - y_[..., 1:3] * filters), -1), -1),-1))

('should be', 0.26)


0.26000000000000001

In [85]:
# 测试object confidence的loss
objects_matcher = y[..., 0:1]
objects_confidences = y[..., 0:1]
objects_confidences_ = y_[..., 0:1]
sqr = np.square(objects_confidences - objects_confidences_)
print(sqr)
print("square shape", sqr.shape)
print("sum as")
sum = np.sum(np.sum(sqr, axis=1), axis=1)
print(sum)

print("mean as")
print(np.mean(sum))
#       , axis=0))


[[[[ 1.]
   [ 0.]]

  [[ 0.]
   [ 0.]]]


 [[[ 0.]
   [ 0.]]

  [[ 0.]
   [ 0.]]]]
('square shape', (2, 2, 2, 1))
sum as
[[ 1.]
 [ 0.]]
mean as
0.5


In [49]:
X = np.array([[0,0]])
np.save(file, (X,y))

In [56]:
X = np.array([1])
[X,y]

[array([1]), array([[[[ 1. ,  0.5,  0.5],
          [ 0. ,  0. ,  0. ]],
 
         [[ 0. ,  0. ,  0. ],
          [ 1. ,  0.2,  0.2]]],
 
 
        [[[ 0. ,  0. ,  0. ],
          [ 0. ,  0. ,  0. ]],
 
         [[ 0. ,  0. ,  0. ],
          [ 0. ,  0. ,  0. ]]]])]

In [50]:
file = "./test.npy"

x_, _ = np.load(file)

In [52]:
print(x_.shape)
print(_.shape)

(1, 2)
(2, 2, 2, 3)


In [60]:
probs = np.zeros(10)
probs[6] = 1
line = np.zeros(13)
line[3:] = probs
line

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.])

In [62]:
"abc".find('d')

-1

In [83]:
# 测试成绩
print(y[...,1:3] * y[..., 0:1])
s1 =np.sum(y[...,1:3] * y[..., 0:1], axis=1)
print(s1)
s2 = np.sum(s1, axis=1)
print (s2)
print(np.mean(s2))

[[[[ 0.5  0.5]
   [ 0.   0. ]]

  [[ 0.   0. ]
   [ 0.2  0.2]]]


 [[[ 0.   0. ]
   [ 0.   0. ]]

  [[ 0.   0. ]
   [ 0.   0. ]]]]
[[[ 0.5  0.5]
  [ 0.2  0.2]]

 [[ 0.   0. ]
  [ 0.   0. ]]]
[[ 0.7  0.7]
 [ 0.   0. ]]
0.35
