# practise np

In [1]:
import numpy as np

In [37]:
X1 = np.array([[1,2],[-1,-2]])
X2 = np.array([[3,4],[-3,-4]])
X1 = np.expand_dims(X1, axis=0)
X2 = np.expand_dims(X2, axis=0)
X = np.vstack((X1, X2))
print X
X.shape
X.T

[[[ 1  2]
  [-1 -2]]

 [[ 3  4]
  [-3 -4]]]


array([[[ 1,  3],
        [-1, -3]],

       [[ 2,  4],
        [-2, -4]]])

In [43]:
y = np.array([[1, 0]])
y_ = np.array([0.6, 0.6])
np.abs(y - y_) < 1


array([[ True,  True]], dtype=bool)

In [44]:
np.shape(y)

(1, 2)

In [47]:
np.int32(np.array([True, False]))

array([1, 0], dtype=int32)

In [13]:
x = np.array([[1,2], [3,4]])
x = np.expand_dims(x, axis=0)
x

array([[[1, 2],
        [3, 4]]])